# Generated by Django 6.0.6 on 2026-08-05 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feecategory_description_feecategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
