# Generated by Django 6.0.6 on 2026-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_studentfee_assigned_date_studentfee_is_paid'),
        ('student', '0003_alter_schoolclass_name_alter_section_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'fee_category'), name='unique_student_fee_category'),
        ),
    ]
