# Generated by Django 6.0.6 on 2026-08-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_studentfee_unique_student_fee_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='paid_amount',
            new_name='amount_paid',
        ),
    ]
