# Generated by Django 6.0.6 on 2026-08-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_rename_paid_amount_feepayment_amount_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
