# Generated by Django 6.1 on 2026-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
